fof

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,22 +1,59 @@
 #!/usr/bin/env bash
-# Install nginx and start it
-apt-get -y install nginx
+# Installs, configures, and starts the server
+# Install nginx
+sudo apt-get -y update
+sudo apt-get -y install nginx -y
 
-# Firewall setting: Allow Nginx to serve on HTTP
-ufw allow 'Nginx HTTP'
+# Start nginx service
+sudo service nginx start
 
-# Create a new index.html file that will be used over the default index.nginx-debian.html
-echo "Holberton School" >> /var/www/html/index.html
+# Configure nginx to listen on port 80
+siudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
 
-#Give the user  ownership to website files
-chown -R $USER:$USER /var/www/html
-chmod -R 755 /var/www
+#configure error page
+echo "Ceci n'est pas une page" > 404.html
+sudo mv 404.html /var/www/html
 
-# Redirect to /redirect_me to a youtube video
-sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
+# Configure nginx to serve the redirect_me file
+sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
+server {
+    listen 80 default_server;
+    listen [::]:80 default_server;
 
-# Setup 404 page
-echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
-sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
+    root /var/www/html;
+    index index.html index.htm index.nginx-debian.html;
 
-service nginx start
+    server_name _;
+    
+    error_page 404 /404.html;
+    location = /404.html{
+       internal;
+    }
+
+    location /redirect_me {
+        return 301 http://www.redirectedpage.com/;
+    }
+}
+EOF'
+
+# Test the nginx configuration for syntax errors
+sudo nginx -t
+
+# Restart nginx service if the configuration is valid
+if [ $? -eq 0 ]
+then
+    sudo service nginx restart
+else
+    echo "Nginx configuration is invalid. Please check the configuration file."
+fi
+
+# Create index file with "Hello World!" message
+echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
+
+# Create redirect_me file with redirect information
+echo -e "HTTP/1.1 301 Moved Permanently\r\nLocation: http://www.redirectedpage.com/\r\n\r\n" | sudo tee /var/www/html/redirect_me > /dev/null
+
+#Restart nginx service
+sudo service nginx restart
+
+
